### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by NephilimDM** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#15]
Hi,
Installation seems fine but  i've an error when homebridge start and try to load the plugin.

`[2018-11-24 10:34:30] ERROR LOADING PLUGIN homebridge-plugin-samsung-air-conditioner:                                                           
[2018-11-24 10:34:30] Error: Could not locate the bindings file. Tried:                                                                         
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/build/binding.node    
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/build/Debug/binding.no
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/build/Release/binding.
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/out/Debug/binding.node
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/Debug/binding.node    
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/out/Release/binding.no
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/Release/binding.node  
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/build/default/binding.
 → /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/compiled/9.2.1/linux/x
    at bindings (/usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-napi/node_mod
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/node_modules/ref-nap
    at Module._compile (module.js:641:30)                                                                                                       
    at Object.Module._extensions..js (module.js:652:10)                                                                                         
    at Module.load (module.js:560:32)                                                                                                           
    at tryModuleLoad (module.js:503:12)                                                                                                         
    at Function.Module._load (module.js:495:3)                                                                                                  
    at Module.require (module.js:585:17)                                                                                                        
    at require (internal/module.js:11:18)                                                                                                       
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/lib/index.js:6:11)  
    at Module._compile (module.js:641:30)                                                                                                       
    at Object.Module._extensions..js (module.js:652:10)                                                                                         
    at Module.load (module.js:560:32)                                                                                                           
    at tryModuleLoad (module.js:503:12)                                                                                                         
    at Function.Module._load (module.js:495:3)                                                                                                  
    at Module.require (module.js:585:17)                                                                                                        
    at require (internal/module.js:11:18)                                                                                                       
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/index.js:1:80)      
    at Module._compile (module.js:641:30)                                                                                                       
    at Object.Module._extensions..js (module.js:652:10)                                                                                         
    at Module.load (module.js:560:32)                                                                                                           
    at tryModuleLoad (module.js:503:12)                                                                                                         
    at Function.Module._load (module.js:495:3)                                                                                                  
    at Module.require (module.js:585:17)                                                                                                        
    at require (internal/module.js:11:18)                                                                                                       
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive/index.js:1:80)      
    at Module._compile (module.js:641:30)                                                                                                       
    at Object.Module._extensions..js (module.js:652:10)                                                                                         
    at Module.load (module.js:560:32)                                                                                                           
    at tryModuleLoad (module.js:503:12)                                                                                                         
    at Function.Module._load (module.js:495:3)                                                                                                  
    at Module.require (module.js:585:17)                                                                                                        
    at require (internal/module.js:11:18)                                                                                                       
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/lib/air-conditioner-api.js:8:19)               
    at Module._compile (module.js:641:30)                                                                                                       
    at Object.Module._extensions..js (module.js:652:10)                                                                                         
[2018-11-24 10:34:30] ====================                 `

Get token work well.
Any idea?

Thanks,
Nephilim

**Comment by SebastianOsinski** [comment]
Hi @NephilimDM What version of node do you have? I haven't encountered that issue myself. I did some digging and found this solution: https://github.com/libxmljs/libxmljs/issues/253#issuecomment-58422367. Maybe it'll work in your case.

**Comment by NephilimDM** [comment]
Hi Sebastian,
thank you so much for your answer.
Your suggestion was to rebuild the net-keepalive module? Because I have an error in this case: 

`gyp: binding.gyp not found (cwd: /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive) while trying to load binding.gyp            
gyp ERR! configure error                                                                                                                                                       
gyp ERR! stack Error: `gyp` failed with exit code: 1                                                                                                                           
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:345:16)                                                                     
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)                                                                                                                     
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)                                                                                   
gyp ERR! System Linux 3.10.105                                                                                                                                                 
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"                                                                                                     
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/net-keepalive                                                                  
gyp ERR! node -v v9.2.1                                                                                                                                                        
gyp ERR! node-gyp -v v3.8.0                                                                                                                                                    
gyp ERR! not ok                                 `

Could it be a version problem?

Thank you again.
Nephilim

**Comment by SebastianOsinski** [comment]
yeah, that was my suggestion. You can try updating node and reinstalling the plugin but I'm not sure if it will work. This plugin is my first encounter with Node so it's quite hard for me to help in this case.

**Comment by NephilimDM** [comment]
Updated homebride and node, now works like a charm.

Thank you.
Nephilim
