### ISSUE TITLE
Token Error: ca md too weak

### ISSUE THREAD

**Issue by SanderBaron** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#24]
Hi,
New to this but finding my way in to it so far! Homebridge up and running on my Raspberry Pi and I installed this great Samsung Plugin!
I receive an error while retrieving the token. Ip of the unit is correct and open port 2878 is confirmed:

pi@raspberrypi:~ $ homebridge-samsung-ac-get-token 192.168.2.16
IP:  192.168.2.16
_tls_common.js:212
        c.context.loadPKCS12(buf);
                  ^

Error: ca md too weak
    at Object.createSecureContext (_tls_common.js:212:19)
    at Object.connect (_tls_wrap.js:1130:48)
    at getToken (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:25:24)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
pi@raspberrypi:~ $ 

I really hope you can put me back on the track! Thanks and keep up this great work!

**Comment by SanderBaron** [comment]
Got a work around for this:
Set tls-cipher "DEFAULT:@SECLEVEL=0" to openssl.cnf
Run script, pull tokens and set back to "DEFAULT:@SECLEVEL=2"

Have it up and running now! Will start new topic for some other problems I ran into...

Thanks!
