### ISSUE TITLE
CA MD too weak

### ISSUE THREAD

**Issue by JeromeMF** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#30]
I'm getting this error: 

_tls_common.js:273
        c.context.loadPKCS12(buf);
                  ^

Error: ca md too weak
    at Object.createSecureContext (_tls_common.js:273:19)
    at Object.connect (_tls_wrap.js:1450:48)
    at getToken (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:25:24)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

and cannot run or find a way to get my token. Do you know why I get CA MD too weak?

**Comment by SebastianOsinski** [comment]
Hi @JeromeMF! What NodeJS version do you use? Issue #21 suggests that the culprit might be NodeJS 12. Please try with 10.16 or similar. Of course this is workaround as final solution would be to fix this for Node 12, but TBH I don't have time to do that right now. Any Pull Requests are welcome though :)

**Comment by JeromeMF** [comment]
It was NodeJS 12. Tried with 10 but no luck either.
Should I try any lower version? 

I've been trying everything to get my AC token with no luck :(

**Comment by peterbuga** [comment]
has anyone tried this https://community.home-assistant.io/t/samsung-ac/11747/127 ?

**Comment by JeromeMF** [comment]
Thanks @peterbuga I'm going to take a look at that and try it as soon as I have some time. But looks promissing.

**Comment by JeromeMF** [comment]
> has anyone tried this https://community.home-assistant.io/t/samsung-ac/11747/127 ?

This worked for me @peterbuga. Thanks a lot. Is it normal that two of my units have the same token?  thanks again

**Comment by peterbuga** [comment]
>  Is it normal that two of my units have the same token? 

as stupid as it might sound maybe you captured somehow the same token twice, if possible try to plug 1 unit at a time and try the capture technique OR wait a longer time (5-10 minutes) between trying to capture the tokens of each unit. just a hunch, might work might not  🤷‍♂️

**Comment by JeromeMF** [comment]
Well it seems they really have the same token. I retried and checked. But since they have different IP and MAC addresses, it doesn't really matters and homebridge can distinguish them with that. I can send the instructions perfectly. It all works. 
I had to use my old raspberrypi 1b with raspbian Jessie (it's not supported on recent models). 
Thanks for your help both @peterbuga and @SebastianOsinski

**Comment by peros550** [comment]
Getting the same error on a newly flashed raspberry running node 10.15.2

**Comment by JeromeMF** [comment]
@peros550 I only got it work using Debian 8 at first and then on a Raspberry Pi 1B since it's the only one I got around that can support Raspbian Jessie. If you have a Raspberry Pi Zero/Zero-W I think you can also use Jessie since I believe it's the same Arm Processor.

**Comment by peros550** [comment]
@JeromeMF many thanks for your feedback!
In current version, this plugin plays nice with node v8. Your advice seems fine and I 'm considering a secondary RPi like you said for this plugin.

Perfect option would be for the plugin to be updated to support latest version of node because  Homebridge requires at least v10.17.0 hence under current circumstances, you cannot have latest versions of Homebridge and this plugin together. 

 @SebastianOsinski has mentioned recently that he will try to create an update, though no ETA yet.

**Comment by JeromeMF** [comment]
Yeah. That's totally the situation. 
If @SebastianOsinski really updates this, it will be amazing. But i'm grateful enough to have something working like this. 
The downside really is to have an old version of homebridge running. 
Glad I could help and I'm sorry if I take long to reply. I'll try to be more careful and I'll help however I can.

**Comment by Jens-Wymeersch** [comment]
@SebastianOsinski @peterbuga I got the A/Cs finally in HomeBridge but I'm not able to change the temperature. I'm only able on/off. Any advise you guys can give ?

**Comment by JeromeMF** [comment]
@Jens-Wymeersch I don't really know why that's happening to you. 
Do you have your config file correctly set-up? 
It should be something like this under accessories: 

`"accessories": [
            {
                     "accessory": "Samsung Air Conditioner",
                     "name": "The name you want for that unit",
                     "ip_address": "XXX.XXX.XXX.XXX",
                     "mac": "XX:XX:XX:XX:XX:XX",
                     "token": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
             },
            ... other accessories you might have ... if it's the last one then remove the **,** just after the last **}**
        ], ... platforms and the rest of the config`

For the temperature, I'm not really sure what is happening to you. If @SebastianOsinski knows, I'm pretty sure he will answer once he can. He's been really helpful.

**Comment by Jens-Wymeersch** [comment]
@JeromeMF  I don't really know what you mean with the *.* part of your reply. I've only these A/Cs in home bridge as I'm fully committed to Home Assistant. I've tried to get the devices into HA without success. Any ideas ?
Secondly, I've followed the guide to the letter but can only put the ACs on or off. 

@SebastianOsinski Any news ?

**Comment by JeromeMF** [comment]
I see. I don't use HomeAssistant. I have the AC configured in Homebridge and the config part I showed you is for Homebridge. I'm afraid I can't really help you with HA since I don't use it. 
If I find time any time soon, I'll install it in any free raspberry pi I got around and I'll try to configure it. But I can't make any promises with all the work I got.

**Comment by JeromeMF** [comment]
I was able to make this work with the latest raspbian (raspios), homebridge and node v14 by changing: 

- Edited **/etc/ssl/openssl.cnf**  and changed **CipherString = DEFAULT@SECLEVEL=1** (default is usualy 2)

- Added **--tls-min-v1.0** in homebridge settings **NODE_OPTIONS** 

Everything has been working fine for a couple of days now. Rebooted my pi a few times and no problems so far.

**Comment by SebastianOsinski** [comment]
Plugin just got updated and should be working with new Node JS versions
