### ISSUE TITLE
Error: The requested accessory 'Samsung Air Conditioner' was not registered by any plugin

### ISSUE THREAD

**Issue by javipe74** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#33]
First of all I want to say a big thank you for this plugin. It has help me a lot to avoid having to use the horrible Samsung App.
last week I installed docker in a new server and since then I'm fighting to make this plugin work again. 

It says the accessory "Samsung Air Conditioner" is not recognised. I have deleted home bridge and installed again but no way. All the other plugins which are registered as platforms are well recognised

I paste the logs from home bridge. Any idea of what may be failing?

[7/16/2020, 2:13:10 PM] Loaded plugin: homebridge-plugin-samsung-air-conditioner@2.0.0
[7/16/2020, 2:13:10 PM] Registering accessory 'homebridge-plugin-samsung-air-conditioner.Samsung Air Conditioner'
[7/16/2020, 2:13:10 PM] ---
[7/16/2020, 2:13:10 PM] Loaded plugin: homebridge-config-ui-x@4.23.2
[7/16/2020, 2:13:10 PM] Registering platform 'homebridge-config-ui-x.config'
[7/16/2020, 2:13:10 PM] Loading 2 platforms...
[7/16/2020, 2:13:11 PM] [Hue] Initializing Hue platform...
[7/16/2020, 2:13:11 PM] [Hue] homebridge-hue v0.11.73, node v12.18.2, homebridge v1.1.1
[7/16/2020, 2:13:11 PM] Loading 2 accessories...
[7/16/2020, 2:13:11 PM] Error loading accessory requested in your config.json at position 1
[7/16/2020, 2:13:11 PM] Error: The requested accessory 'Samsung Air Conditioner' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:347:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:330:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:156:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
[7/16/2020, 2:13:11 PM] Got SIGTERM, shutting down Homebridge...

**Comment by javipe74** [comment]
After a week I decide to rewrite the config.json manually instead of copy/paste and now it works. I suppose some hidden character was causing the issue. Sorry for the misunderstanding.
