### ISSUE TITLE
Cannot get token

### ISSUE THREAD

**Issue by gcherem** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#35]
Hi,

When I run `homebridge-samsung-ac-get token 192.168.11.21`, I get the following error:

`IP: 192.168.11.21`
`Error occured: connect ECONNREFUSED 192.168.11.21:2878`

Any idea?

**Comment by zozo6015** [comment]
Hello, 

When I am running homebridge-samsung-ac-get-token 10.0.24.124 I am getting the following error:

```
homebridge-samsung-ac-get-token 10.0.24.124
IP:  10.0.24.124
_tls_common.js:273
        c.context.loadPKCS12(buf);
                  ^

Error: ca md too weak
    at Object.createSecureContext (_tls_common.js:273:19)
    at Object.connect (_tls_wrap.js:1580:48)
    at getToken (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:25:24)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:52:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by m1hah** [comment]
> Hi,
> 
> When I run `homebridge-samsung-ac-get token 192.168.11.21`, I get the following error:
> 
> `IP: 192.168.11.21`
> `Error occured: connect ECONNREFUSED 192.168.11.21:2878`
> 
> Any idea?

Same issues here. Did you figure it out?

**Comment by m1hah** [comment]
> Hello,
> 
> When I am running homebridge-samsung-ac-get-token 10.0.24.124 I am getting the following error:
> 
> ```
> homebridge-samsung-ac-get-token 10.0.24.124
> IP:  10.0.24.124
> _tls_common.js:273
>         c.context.loadPKCS12(buf);
>                   ^
> 
> Error: ca md too weak
>     at Object.createSecureContext (_tls_common.js:273:19)
>     at Object.connect (_tls_wrap.js:1580:48)
>     at getToken (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:25:24)
>     at Object.<anonymous> (/usr/lib/node_modules/homebridge-plugin-samsung-air-conditioner/bin/ac-get-token.js:52:1)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
>     at internal/main/run_main_module.js:17:47
> ```

Please check another issue here, the solution fixes the issue

**Comment by coniglioemanuele** [comment]
seems relate to this:

i got same error on raspian buster after whole upgrading last week end.
error is due to openssl that doesn't support anymore tls1.
to solve i edited manually the plugin in lib/air-conditioner-api.js between line 45-46 add: secureProtocol: 'TLSv1_method',
to get also ac-get-token work i add also in bin/ac-get-token.js

this force connection by tls1, is a workaround and depend on your tls version on ac split... tring curl -v --tlsv1.0 https://yourip:2878 you should see

**Comment by SebastianOsinski** [comment]
Newest version of the plugin should work fine without needing to tweak it manually
