### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by XxGuI2eNxX** [SebastianOsinski/HomebridgePluginSamsungAirConditioner#45]
How to install plugin?

USER: homebridge
DIR: /volume2/homebridge
CMD: npm install --save homebridge-plugin-samsung-air-conditioner@3.1.0

[##################] - reify:ffi-napi: timing reifyNode:node_modules/homebridge-plugin-sam
> ffi-napi@4.0.3 install
> node-gyp-build

gyp[##################] \ reify:ffi-napi: timing reifyNode:node_modules/homebridge-plugin-s ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
gyp ERR! stack     at /volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
gyp ERR! stack     at /volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
gyp ERR! stack     at /volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
gyp ERR! stack     at /volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 3.10.108
gyp ERR! command "/volume2/@appstore/homebridge/app/bin/node" "/volume2/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume2/homebridge/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/ffi-napi
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume2/homebridge/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/ffi-napi
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2023-06-13T18_41_56_971Z-debug-0.log

Operation failed. Please review log for details.

**Comment by stalkerj** [comment]
Hello. I'm trying to reinstall plugin and got an error.

USER: homebridge
DIR: /volume1/homebridge
CMD: npm install --save homebridge-plugin-samsung-air-conditioner@3.1.0

[##################] \ reify:ffi-napi: timing reifyNode:node_modules/homebridge-plugin
> ffi-napi@4.0.3 install
> node-gyp-build

[##################] - reify:ffi-napi: timing reifyNode:node_modules/homebridge-plugin
gyp ERR! build error - reify:ffi-napi: timing reifyNode:node_modules/homebridge-plugin
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:16:17)
gyp ERR! stack at which (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/lib/index.js:77:9)
gyp ERR! stack at async doWhich (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:112:22)
gyp ERR! stack at async loadConfigGypi (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:77:7)
gyp ERR! stack at async build (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:35:3)
gyp ERR! stack at async run (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
gyp ERR! System Linux 4.4.302+
gyp ERR! command "/volume1/@appstore/Node.js_v20/usr/local/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /volume1/homebridge/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/ffi-napi
gyp ERR! node -v v20.9.0
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/homebridge-plugin-samsung-air-conditioner/node_modules/ffi-napi
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in: /var/packages/homebridge/home/.npm/_logs/2024-04-26T10_41_04_286Z-debug-0.log

Operation failed with code 1.
You can download this log file for future reference.
See https://github.com/homebridge/homebridge-config-ui-x/wiki/Troubleshooting for help

**Comment by stalkerj** [comment]
current node version is 20.9.0
Can you fix it?

**Comment by stalkerj** [comment]
This one would help us as I understood
https://github.com/homebridge/homebridge-syno-spk/wiki/DSM-7:-Enable-Compiling-Of-Native-Modules

**Comment by stalkerj** [comment]
> This one would help us as I understood https://github.com/homebridge/homebridge-syno-spk/wiki/DSM-7:-Enable-Compiling-Of-Native-Modules

I made it in my Synology NAS and plugin installed and working well now
